env:
  TERM: xterm-256color

font:
  normal:
    family: Source Code Pro for Powerline
    style: Semibold
  size: 12.0

window:
  dynamic_padding: true

  live_config_reload: true

selection:
  save_to_clipboard: true

mouse_bindings:
  - { mouse: Right, action: PasteSelection }

# GNOME Terminal Tango Dark
# Match-dark-aliz primary colors
colors:
  primary:
    background: '0x262626'
    foreground: '0xcbbfbf'

  # Normal colors
  normal:
    black: '0x2e3436'
    red: '0xcc0000'
    green: '0x4e9a06'
    yellow: '0xc4a000'
    blue: '0x3465a4'
    magenta: '0x75507b'
    cyan: '0x06989a'
    white: '0xd3d7cf'

  # Bright colors
  bright:
    black: '0x555753'
    red: '0xef2929'
    green: '0x8ae234'
    yellow: '0xfce94f'
    blue: '0x729fcf'
    magenta: '0xad7fa8'
    cyan: '0x34e2e2'
    white: '0xeeeeec'

